"""Pydantic Schemas for Document Analysis API"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class PurchaseOrderResponse(BaseModel):
    """Purchase Order response schema"""
    id: int
    po_number: str
    description: str
    serial_numbers: List[str]
    cached: bool = Field(..., description="Whether description was retrieved from cache")
    llm_used: bool = Field(..., description="Whether LLM was used to generate description")
    text_length: int = Field(..., description="Length of original text content")


class DocumentResponse(BaseModel):
    """Document response schema"""
    id: int
    supplier: str
    invoice_number: str
    document_type: str
    image_path: str
    original_filename: Optional[str] = None


class AnalysisStatistics(BaseModel):
    """Analysis statistics schema"""
    total_pos: int = Field(..., description="Total number of Purchase Orders found")
    cached_descriptions: int = Field(..., description="Number of descriptions retrieved from cache")
    new_descriptions: int = Field(..., description="Number of new descriptions generated by LLM")
    total_serial_numbers: int = Field(..., description="Total serial numbers extracted")


class InvoiceAnalysisResponse(BaseModel):
    """Complete invoice analysis response"""
    success: bool
    document: DocumentResponse
    purchase_orders: List[PurchaseOrderResponse]
    statistics: AnalysisStatistics
    error: Optional[str] = None
    step: Optional[str] = None


class InvoiceAnalysisRequest(BaseModel):
    """Invoice analysis request (for OCR text when not using file upload)"""
    ocr_text: str = Field(..., description="OCR text extracted from invoice image")
    document_type: str = Field(default="invoice", description="Type of document being analyzed")


class DocumentListResponse(BaseModel):
    """Response for document listing"""
    id: int
    document_type: str
    document_number: str
    supplier: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class PurchaseOrderCacheResponse(BaseModel):
    """Purchase Order cache response"""
    id: int
    po_number: str
    description: Optional[str]
    serial_numbers: List[str] = Field(default_factory=list)
    created_at: datetime
    updated_at: datetime
    has_description: bool = Field(..., description="Whether PO has cached description")
    
    class Config:
        from_attributes = True


class CacheStatisticsResponse(BaseModel):
    """LLM cache statistics response"""
    total_purchase_orders: int
    cached_descriptions: int
    cache_hit_rate: float = Field(..., description="Percentage of POs with cached descriptions")
    cache_miss_count: int


class ValidationResult(BaseModel):
    """OCR parsing validation result"""
    valid: bool
    issues: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    po_count: int
    total_serial_numbers: int


class ParsedPurchaseOrderResponse(BaseModel):
    """Parsed Purchase Order data"""
    po_number: str
    text: str = Field(..., description="Cleaned text content for this PO")
    serial_numbers: List[str]


class ParsedInvoiceResponse(BaseModel):
    """Parsed invoice data from deterministic parsing"""
    supplier: str
    invoice_number: str
    purchase_orders: List[ParsedPurchaseOrderResponse]
    validation: ValidationResult


class LLMGenerationRequest(BaseModel):
    """Request for LLM description generation"""
    po_number: str
    po_text: str = Field(..., description="Clean text content for Purchase Order")


class LLMGenerationResponse(BaseModel):
    """Response from LLM description generation"""
    success: bool
    description: str
    word_count: Optional[int] = None
    model_used: Optional[str] = None
    error: Optional[str] = None


class ErrorResponse(BaseModel):
    """Standard error response"""
    success: bool = False
    error: str
    step: Optional[str] = None
    details: Optional[Dict[str, Any]] = None
